[build]
builder = "nixpacks"

[deploy]
startCommand = "streamlit run disc_style.py --server.port $PORT --server.address 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "never"
